CREATE TABLE `discord_channel` 
(
    `id` INT(36) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `channel_id` INT(36) NOT NULL,
    `channel_state` TINYINT(1) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `discord_user`
(
    `id` INT(36) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `discord_id` INT(36) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `historical_moment`
(
    `id` INT(36) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `type` VARCHAR(100) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `moment_team_id` INT(36) NOT NULL,
    `against_team_id` INT(36) NOT NULL,
    `player_name` VARCHAR(100),
    `clip_link` VARCHAR(200) NOT NULL,
    `game_index_link` VARCHAR(200) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `jeopardy_account`
(
    `id` INT(36) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `discord_id` INT(36) NOT NULL,
    `correct_answers` INT(36) NOT NULL,
    `wrong_answers` INT(36) NOT NULL,
    `money` INT(36) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `pbe_team`
(
    `id` INT(36) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `city_name` VARCHAR(100) NOT NULL,
    `team_name` VARCHAR(100) NOT NULL,
    `abbreviation` VARCHAR(5) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);